import { useEffect, useState } from 'react';
import QRCode from 'qrcode';

// Renders a downloadable QR that decodes to the worshipper-facing site.
// Use it on pew cards, project before service, share on socials.
export default function QrCodeCard() {
  const [pngDataUrl, setPngDataUrl] = useState(null);
  const [error, setError] = useState(null);

  // The worshipper site = same origin + the configured base path.
  // In production this is "https://colporteur.github.io/wfumc-bulletin/".
  // In local dev it's "http://localhost:5173/".
  const worshipperUrl =
    typeof window !== 'undefined'
      ? `${window.location.origin}${import.meta.env.BASE_URL}`
      : '';

  useEffect(() => {
    if (!worshipperUrl) return;
    let cancelled = false;
    QRCode.toDataURL(worshipperUrl, {
      width: 512,
      margin: 2,
      errorCorrectionLevel: 'M',
      color: {
        dark: '#5b1a1a', // church maroon — recognizable, prints well
        light: '#ffffff',
      },
    })
      .then((url) => {
        if (!cancelled) setPngDataUrl(url);
      })
      .catch((e) => {
        if (!cancelled) setError(e.message || 'Failed to generate QR.');
      });
    return () => {
      cancelled = true;
    };
  }, [worshipperUrl]);

  return (
    <div className="card">
      <h2 className="font-serif text-lg text-umc-900">
        QR code for the bulletin
      </h2>
      <p className="text-sm text-gray-600 mt-1">
        Print on pew cards, project before the service, or include in any
        printed material. Scanning with a phone camera opens the
        worshipper-facing bulletin.
      </p>

      {error && (
        <p className="text-sm text-red-600 mt-3">{error}</p>
      )}

      {pngDataUrl ? (
        <div className="mt-4 flex flex-col items-center gap-3">
          <img
            src={pngDataUrl}
            alt="QR code linking to the worshipper bulletin"
            className="w-48 h-48 border border-gray-200 rounded"
          />
          <a
            href={pngDataUrl}
            download="wfumc-bulletin-qr.png"
            className="btn-secondary text-sm"
          >
            Download PNG
          </a>
          <p className="text-xs text-gray-500 break-all text-center max-w-xs">
            Decodes to:{' '}
            <a
              href={worshipperUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-umc-700 underline"
            >
              {worshipperUrl}
            </a>
          </p>
        </div>
      ) : !error ? (
        <p className="text-sm text-gray-400 mt-4">Generating…</p>
      ) : null}

      <p className="text-xs text-gray-400 mt-4">
        The image is 512×512 PNG, generated in your browser. The dark color
        is the church maroon. Standard QR readers including all phone
        cameras handle non-black QRs fine, but if you ever get a scan
        failure on weird scanners, a black-and-white version can be
        re-generated by editing this card.
      </p>
    </div>
  );
}
